user can specify a python wrapper via environment BUILDTEST_PYTHON to use when running buildtest. This is checked before starting buildtest and creates a subshell.
We fix a check during system detection to read value from BUILDTEST_PYTHON instead
of shutil.which('python') since we want to get value of python interpretter that was
executed

diff --git a/bin/buildtest b/bin/buildtest
--- a/bin/buildtest
+++ b/bin/buildtest
@@ -1,4 +1,24 @@
-#!/usr/bin/env python3
+#!/bin/sh
+
+# This file is bilingual. The following shell code finds our preferred python.
+# Following line is a shell no-op, and starts a multi-line Python comment.
+# See https://stackoverflow.com/a/47886254
+
+""":"
+# preferred pythons for running buildtest
+PREFERRED_PYTHONS="python3 python"
+
+# Find a suitable python interpreter (adapt for your specific needs)
+for cmd in "${BUILDTEST_PYTHON:-}" ${PREFERRED_PYTHONS} ; do
+    if command -v > /dev/null "$cmd"; then
+        export BUILDTEST_PYTHON="$(command -v "$cmd")"
+        exec "${BUILDTEST_PYTHON}" "$0" "$@"
+    fi
+done
+
+echo "==> Error: buildtest could not find a python interpreter!" >&2
+exit 1
+":"""
 
 import os
 import sys
